### ISSUE TITLE
python2 or python3 or compatible?

### ISSUE THREAD

**Issue by threadshare** [EOSTestMonster/eostestmonster#4]
我们这个脚本现在用的是python2,  这样是为了方便在默认的Linux环境中跑么?
我们有没有意向做一些兼容 或者使用python3?

**Comment by threadshare** [comment]
要是有做兼容的打算, 我可以帮忙弄下

**Comment by noprom** [comment]
欢迎哈，直接提交修改就是了，我们测试一下就合并。

**Comment by EOSBIXIN** [comment]
欢迎完善，最好是保持简单，在一个strat_monster.py里面实现

**Comment by EOSBIXIN** [comment]
this closed by #3
